[[service]]
category = "bitcoin"
api-key = "xxx"
endpoint = "https://api.coingecko.com/api/v3/coins/markets"

[service.fields]
field1 = "JSONPath"


[[service]]
category = "bitcoin"
api-key = "xxx"
endpoint = "https://api.coingecko.com/api/v3/coins/markets"


[service.fields]
field1 = "JSONPath"

